name: switch_app_icon
description: A production-ready Flutter plugin to dynamically switch the application launcher icon at runtime.
version: 0.0.6
homepage: https://github.com/thanseer02/switch_app_icon

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.switch_app_icon.switch_app_icon
        pluginClass: SwitchAppIconPlugin
      ios:
        pluginClass: SwitchAppIconPlugin
